name: Main Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

# Prevent running builds for the same branch in parallel
# New workflows will cancel existing workflows…
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build (main)
    uses: ./.github/workflows/build.yml

  test:
    name: Test (main)
    uses: ./.github/workflows/test.yml
