name: PR Pipeline

on:
  pull_request:

# Prevent running checks for the same branch in parallel
# New workflows will cancel existing workflows…
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint (preview)
    uses: ./.github/workflows/lint.yml

  build:
    name: Build (preview)
    uses: ./.github/workflows/build.yml

  test:
    name: Test (preview)
    uses: ./.github/workflows/test.yml
