name: Release

on:
  workflow_call:

permissions:
  pull-requests: write
  issues: write
  contents: write
  packages: write

jobs:
  release:
    # Prevents changesets action from creating a PR on forks
    if: github.repository == 'inventage/lit-i18next'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0
          persist-credentials: false

      - name: Create .npmrc
        run: |
          cat << EOF > "$HOME/.npmrc"
            //registry.npmjs.org/:_authToken=$NPM_TOKEN
          EOF
        env:
          NPM_TOKEN: ${{ secrets.NPM_INVENTAGE_ORG_PUBLISH }}

      - uses: ./.github/actions/setup-node-and-dependencies

      - name: Run Build
        run: npm run build

      - name: Create Release PR or publish to NPM
        uses: changesets/action@v1
        with:
          publish: npm run release
          version: npm run version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
