name: Test

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        i18next_version: [23, 24, 25]
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-node-and-dependencies

      - name: Install i18next version ${{ matrix.i18next_version }}
        run: npm i -D i18next@${{ matrix.i18next_version }}

      # Disable man-db triggers
      # @see https://github.com/actions/runner-images/issues/10977#issuecomment-2681219742
      - name: Setup Playwright
        run: |
          echo 'set man-db/auto-update false' | sudo debconf-communicate >/dev/null
          sudo dpkg-reconfigure man-db
          npx playwright install --only-shell --with-deps chromium

      - name: Run Tests
        run: npx playwright install-deps && npm test



